### ISSUE TITLE
Update bikeshed install steps for .travis.yml

### ISSUE THREAD

**Issue by inexorabletash** [rtoy/auto-deploy-spec#4]
Per @tabatkins over in https://github.com/w3c/FileAPI/commit/4f9f399aa5c0ec33851416fedd5fb50a0c5152fc the steps can just be:

```
pip install bikeshed
bikeshed update
```

No need for a clone.

(I haven't tried this with my repos yet, though)

**Comment by inexorabletash** [comment]
Also, should bump python version to 3.7

**Comment by rtoy** [comment]
Yes, I just updated webaudio CI to do exactly that. :-)

I'll update this soon.
